// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzCodeReview
{
    internal sealed partial class Vsix
    {
        public const string Id = "OzCodeReview.69775100-90e3-4482-9e54-02a212fa3d3c";
        public const string Name = "OzCodeReview";
        public const string Description = @"This extension allows you to create code review directly inside Visual Studio and assign them to an user. This user can also see them directly inside Visual Studio and comment or update their status.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Gregoire Larreur";
        public const string Tags = "";
    }
}
