// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OzCodeReview
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string OzCodeReviewString = "a4621af1-3bc8-4167-a1d1-408cdded0f0c";
        public static Guid OzCodeReview = new Guid(OzCodeReviewString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OzMenuGroup = 0x0001;
        public const int InsertCodeCommentCommand = 0x0100;
        public const int OpenCodeCommentsCommand = 0x0200;
    }
}